create_vacation:
  name: Create vacation
  description: >-
    Create a vacation on the selected device. If end date is not specified, the
    vacation is going to be deleted.
  fields:
    device_id:
      name: Device
      description: Ariston device on which to create the vacation.
      required: true
      selector:
        device:
          integration: ariston
          domain: climate
    end_date:
      name: End date
      description: Date the vacation ends in the YYYY-mm-dd format.
      selector:
        text:
