create_vacation:
  name: Create vacation
  description: >-
    Create a vacation on the selected device. If end datetime is not specified, the
    vacation is going to be deleted.
  fields:
    device_id:
      name: Device
      description: Ariston device on which to create the vacation.
      required: true
      selector:
        device:
          integration: ariston
          domain: climate
    end_datetime:
      name: End date
      description: >-
        Datetime the vacation ends in the YYYY-mm-dd HH:MM:SS format.
      selector:
        text:
